steps:
  # Deploy to Cloud Run using source
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "freightfloo-app"
      - "--source"
      - "."
      - "--platform"
      - "managed"
      - "--region"
      - "europe-west1"
      - "--allow-unauthenticated"
      - "--port"
      - "3000"
      - "--min-instances"
      - "1"
      - "--max-instances"
      - "10"
      - "--set-env-vars"
      - "NODE_ENV=production,NEXTAUTH_SECRET=aoIvyahpA5v2QlNP5FGaieNbRCj4iDNJm8rFGKJZdHNrVLMaiUakt+Z2IQU="
      - "--set-secrets"
      - "DATABASE_URL=DATABASE_URL:latest,RESEND_API_KEY=RESEND_API_KEY:latest"

options:
  logging: CLOUD_LOGGING_ONLY
